### ISSUE TITLE
Server start fails, cant invoke error

### ISSUE THREAD

**Issue by Thrillerninja** [ruscalworld/fabric-exporter#15]
Fabric 1.12.1, Version: 1.0.11

The starting of the server fails, I can't find a problem on my server

This is the error in the log:
java.lang.NullPointerException: Cannot invoke "io.prometheus.client.exporter.HTTPServer.close()" because the return value of "ru.ruscalworld.fabricexporter.FabricExporter.getHttpServer()" is null
        at ru.ruscalworld.fabricexporter.FabricExporter.lambda$onInitialize$1(FabricExporter.java:66) ~[fabricexporter-1.0.11.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.3.1+6c1df36019-7fe4167b7d3b659f.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cjp000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:8648) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:561) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:735) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]

**Comment by Thrillerninja** [comment]
Ok, update: After a removing, starting and re adding the mod the server starts normally
